# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 267f2945f7be987e5ecbf1aa03c75b7c8bebd991a05ea745a603f3177a6c61fa1d889f173d7f7511c86ca765f3526d4f0b2428e06b0af573bb055af654fb19b4

test:
  secret_key_base: 1400b44e1f5842339ae4ef641f476b3189cf2fcf43228b5a6df5201cbe54898583d1cb8c10943dd5278624b63b52a7f5c615d573ddae3a4494d4afe13ec0b251

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
